### ISSUE TITLE
Project not working on windows!

### ISSUE THREAD

**Issue by YoyoAnandra** [mozilla/science.mozilla.org#588] opened 2017-03-05 13:01 UTC
Getting Error:

ERROR in ./js/backend.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../config/env.generated.json in C:\Windows\System32\science.mozilla.org/app\js
 @ ./js/backend.js 7:20-62

> science.mozilla.org@1.0.0 build:scss C:\Windows\System32\science.mozilla.org
> node-sass app/scss/main.scss dist/css/main.css && postcss --use autoprefixer --autoprefixer.browsers 'last 3 versions' -o dist/css/main.css dist/css/main.css

Rendering Complete, saving .css file...
Wrote CSS to C:\Windows\System32\science.mozilla.org\dist\css\main.css
Usage: C:\Program Files\nodejs\node.exe C:\Windows\System32\science.mozilla.org\node_modules\postcss-cli-simple\bin\postcss -use plugin [--config|-c config.json]
[--output|-o output.css] [input.css]

Options:
  -c, --config       JSON file with plugin configuration
  -u, --use          postcss plugin name (can be used multiple times)
  -o, --output       Output file
  -m, --map          Source map
  -s, --syntax       Alternative input syntax parser
  -p, --parser       Alternative CSS parser
  -t, --stringifier  Alternative output stringifier
  -v, --version      Show version number                                                                                                                  [boolean]
  -h, --help         Show help                                                                                                                            [boolean]

Examples:
  postcss --use autoprefixer -c options.json -o screen.css screen.css                Use autoprefixer as a postcss plugin
  postcss --use autoprefixer --autoprefixer.browsers "> 5%" -o screen.css            Pass plugin parameters in plugin.option notation
  screen.css

Please specify a single input file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:scss"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! science.mozilla.org@1.0.0 build:scss: `node-sass app/scss/main.scss dist/css/main.css && postcss --use autoprefixer --autoprefixer.browsers 'last 3 versions' -o dist/css/main.css dist/css/main.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the science.mozilla.org@1.0.0 build:scss script 'node-sass app/scss/main.scss dist/css/main.css && postcss --use autoprefixer --autoprefixer.browsers 'last 3 versions' -o dist/css/main.css dist/css/main.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the science.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass app/scss/main.scss dist/css/main.css && postcss --use autoprefixer --autoprefixer.browsers 'last 3 versions' -o dist/css/main.css dist/css/main.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs science.mozilla.org
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls science.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2017-03-05T12_29_29_216Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! science.mozilla.org@1.0.0 build: `npm run build:config && npm run build:js && npm run build:scss && npm run build:static && npm run build:assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the science.mozilla.org@1.0.0 build script 'npm run build:config && npm run build:js && npm run build:scss && npm run build:static && npm run build:assets'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the science.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:config && npm run build:js && npm run build:scss && npm run build:static && npm run build:assets
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs science.mozilla.org
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls science.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2017-03-05T12_29_29_509Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! science.mozilla.org@1.0.0 start: `npm run build && npm-run-all --parallel server:dev watch:**`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the science.mozilla.org@1.0.0 start script 'npm run build && npm-run-all --parallel server:dev watch:**'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the science.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm-run-all --parallel server:dev watch:**
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs science.mozilla.org
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls science.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2017-03-05T12_29_29_688Z-debug.log

**Comment by alanmoo** [comment] 2017-03-05 16:40
Duplicate of #567. We'd love some help get this working if you have time, it's actually a high priority to enable other contributors

**Closed by alanmoo** 2017-03-05 16:40 UTC

**Comment by YoyoAnandra** [comment] 2017-03-06 19:23
but how can i run the build!

**Comment by alanmoo** [comment] 2017-03-06 20:02
That's what we need help with; it looks like the problem is with PostCSS on Windows, so we need some sort of fix/alternative that does work on Windows.

**Comment by KameyHameyHa** [comment] 2017-03-12 10:13
Had the same problem and was forced to work on Linux instead.

**Comment by alanmoo** [comment] 2017-03-13 00:04
Troubleshooting problems like this is a great way to get real-world development experience if either of you can help! Coding isn't all loops and objects; a lot of the time it's a matter of finding the pieces that work together.
